name: CI and DevSecOps - PR

on:
  workflow_dispatch:  
  pull_request:
    branches: [ master ]

jobs:
  build:
   
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Source

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1.403
      
    - name: Install dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal
 
  scan:
    
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Source
    
    steps:
    - uses: actions/checkout@v2

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
    - name: Check password
      uses: AlicanAkkus/pinder-action@1.0.0
      
    - name: Git Anti Virus Scan
      uses: djdefi/gitavscan@2
      with:
        # Full history scan
        full: '--full'
    
